### ISSUE TITLE
Change of date for Sustainable Supply chain event 

### ISSUE THREAD

**Issue by mayalouise** [ledgerz/berlinblockchainweek#7]
Proposer: Maya (Centrifuge)
Event name: Sustainable Supply chains 

Hi everyone! 
I would like to move our event to Thursday 6th eve, is that ok?

**Comment by tobowers** [comment]
👍 from me :). A process question on here: should the schedule google sheet be like a wiki where if you're changing your time, you just do it?

**Comment by yoshibase** [comment]
👍
