### ISSUE TITLE
Open Source Incentivization and Sustainability with OSCoin

### ISSUE THREAD

**Issue by oxnr** [ledgerz/berlinblockchainweek#8]
**Proposer:** OScoin (Eleftherios Diakomichalis / @lftherios) 
**Event name:** Open Source Incentivization and Sustainability with OSCoin
**Goals:** Understand the problems that OScoin is trying to solve.
**Content details:** What we are building and the general problem of open source incentivization. Incentivization and governance models we imagine for Open Source. Technical aspects of the platform we intend to build. Self-amending core language we call radicle.

Disclaimer: We're not building on Ethereum but have something great that all open-source community can benefit from.

**Comment by yoshibase** [comment]
👍
