### ISSUE TITLE
On-chain/Decentralized Governance

### ISSUE THREAD

**Issue by NathaliaScherer** [ledgerz/berlinblockchainweek#9]
Proposer: DAOstack
Event name: On-chain Governance

Goals: We hope to find more projects interested in building dialogue around the main pain points/ challenges of on-chain governance for the Ethereum community (or beyond it), interoperability possibilities and introduce DAOstack's (and/or other's) protocols.

Content details (proposed but flexible depending on other orgs that want to join on hosting it): 
- Open discussion: main pain points of on chain governance
- Challenge & protocol for improvement: scalability vs governance
- Introducing Arc, Alchemy (dApp for decentralized resource management built on top of DAOstack, alfa is an ongoing pilot on mainnet) and the DAO stack layers.
- Discussing how a DAOstack DAO can be used to govern Gnosis' dutchX exchange and the ongoing Gnosis challenge.

**Comment by yoshibase** [comment]
👍
